version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
    - app-tier
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
    - app-tier
    environment:
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181

  mongo:
    container_name: 'local-mongo'
    image: 'mongo:latest'
    networks:
    - app-tier
    ports:
    - "27017:27017"

  problem_catalog:
    container_name: 'problem-catalog'
    image: 'isvara/problem-catalog:latest'
    networks:
    - app-tier
    ports:
    - "8081:8081"
    depends_on:
    - kafka
    - mongo
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - MONGO_DB_HOST=mongo:27017

  problem:
    container_name: 'problem'
    image: 'isvara/problem:latest'
    networks:
    - app-tier
    ports:
    - "8080:8080"
    depends_on:
    - kafka
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  challenge:
    container_name: 'challenge'
    image: 'isvara/challenge:latest'
    networks:
    - app-tier
    ports:
    - "8082:8082"
    depends_on:
    - kafka
    environment:
    - KAFKA_BOOTSTRAP_SERVERS=kafka:9092