server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      force: true

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: 27017
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: problem-catalog-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer